name: flutter_paddle_ocr
description: "On-device OCR for Flutter, powered by PaddleOCR + Paddle Lite. Supports PP-OCRv2/v3 detection, angle classification, and recognition."
version: 0.0.1
homepage: https://github.com/phanbaohuy96/flutter-paddle-ocr

environment:
  sdk: ^3.10.8
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.huyphan.flutter_paddle_ocr
        pluginClass: FlutterPaddleOcrPlugin
      ios:
        pluginClass: FlutterPaddleOcrPlugin
